Repository smile-io/ember-polaris, pull requests merged in 2020-11, with the labels that each got.

#672 Update CalloutCard component
  addon/components/polaris-callout-card.hbs
  addon/components/polaris-callout-card.js
  docs/callout-card.md
  tests/integration/components/polaris-callout-card-test.js
Labels: enhancement

#671 Update PolarisCaption component
  addon/components/polaris-caption.hbs
  addon/components/polaris-caption.js
  tests/integration/components/polaris-caption-test.js
Labels: breaking, enhancement

#678 Add support for new design language
  addon/components/polaris-action-list.hbs
  addon/components/polaris-action-list.js
  addon/components/polaris-action-list/item.js
  addon/components/polaris-action-list/section.hbs
  addon/components/polaris-action-list/section.js
  addon/components/polaris-icon.js
  addon/services/polaris-app-provider.js
  addon/utils/color-new-design-language.js
  app/services/polaris-app-provider.js
  app/utils/color-new-design-language.js
  tests/integration/components/polaris-action-list-test.js
  tests/integration/components/polaris-icon-test.js
Labels: enhancement

#677 Update private UnstyledLink component
  addon/components/polaris-action-list/item.hbs
  addon/components/polaris-unstyled-link.hbs
  addon/components/polaris-unstyled-link.js
  addon/templates/components/polaris-breadcrumbs.hbs
  addon/templates/components/polaris-button.hbs
  addon/templates/components/polaris-resource-list/item.hbs
  addon/templates/components/polaris-unstyled-link.hbs
  tests/integration/components/polaris-unstyled-link-test.js
  yarn.lock
Labels: breaking, enhancement

#681 Update ember-basic-dropdown to latest release
  addon/templates/components/polaris-popover.hbs
  addon/templates/components/polaris-popover/content.hbs
  config/ember-try.js
  package.json
  yarn.lock
Labels: dependencies

#676 Update PolarisBadge
  addon/components/polaris-badge.hbs
  addon/components/polaris-badge.js
  addon/utils/decorators/arg.js
  tests/integration/components/polaris-badge-test.js
Labels: breaking, enhancement

#675 Update polaris breadcrumbs
  addon/components/polaris-breadcrumbs.hbs
  addon/components/polaris-breadcrumbs.js
  addon/templates/components/polaris-breadcrumbs.hbs
  tests/integration/components/polaris-breadcrumbs-test.js
Labels: breaking, enhancement

#683 Update polaris banner
  addon/components/polaris-banner.hbs
  addon/components/polaris-banner.js
  addon/templates/components/polaris-banner.hbs
  tests/integration/components/polaris-banner-test.js
Labels: breaking, enhancement
